=== pypi-data/pypi-mirror-99/packages/sapporo/sapporo-1.0.13-py3-none-any.whl/sapporo/service-info.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Schema for sapporo service-info",
  "type": "object",
  "properties": {
    "workflow_type_versions": {
      "type": "object",
      "properties": {
        "additionalProperties": {
          "type": "object",
          "properties": {
            "workflow_type_version": {
              "type": "array",
              "items": {
                "type": "string"
              }
            }
          },
          "required": ["workflow_type_version"]
        }
      }
    },
    "supported_filesystem_protocols": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "default_workflow_engine_parameters": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string"
          },
          "type": {
            "type": "string"
          },
          "default_value": {
            "type": "string"
          }
        },
        "required": ["name", "type", "default_value"]
      }
    },
    "workflow_engine_versions": {
      "additionalProperties": {
        "type": "string"
      }
    },
    "auth_instructions_url": {
      "type": "string"
    },
    "contact_info_url": {
      "type": "string"
    },
    "tags": {
      "type": "object",
      "additionalProperties": true
    },
    "additionalProperties": true
  },
  "required": [
    "workflow_type_versions",
    "supported_filesystem_protocols",
    "default_workflow_engine_parameters",
    "workflow_engine_versions",
    "auth_instructions_url",
    "contact_info_url",
    "tags"
  ]
}

=== pypi-data/pypi-mirror-99/packages/sapporo/sapporo-1.0.13-py3-none-any.whl/sapporo/service-info.json
{
  "workflow_type_versions": {
    "CWL": {
      "workflow_type_version": ["v1.0", "v1.1", "v1.1.0-dev1"]
    },
    "Nextflow": {
      "workflow_type_version": ["v1.0"]
    },
    "Snakemake": {
      "workflow_type_version": ["v1.0"]
    },
    "WDL": {
      "workflow_type_version": ["1.0"]
    }
  },
  "supported_filesystem_protocols": ["http", "https", "file", "s3"],
  "default_workflow_engine_parameters": [],
  "workflow_engine_versions": {
    "cwltool": "1.0.20191225192155",
    "nextflow": "21.01.1-edge",
    "toil (experimental)": "4.1.0",
    "cromwell": "55",
    "snakemake": "v5.32.0",
    "ep3 (experimental)": "v1.0.0"
  },
  "auth_instructions_url": "https://github.com/ddbj/sapporo-service",
  "contact_info_url": "https://github.com/ddbj/sapporo-service",
  "tags": {
    "wes_name": "sapporo"
  }
}
